apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gary
  name: dind
  labels:
    app: dind
spec:
  replicas: 1
  template:
    metadata:
      name: dind
      labels:
        app: dind
    spec:
      containers:
        - name: dind
          image: docker:dind
          securityContext:
            privileged: true
  selector:
    matchLabels:
      app: dind
---
apiVersion: v1
kind: Service
metadata:
  namespace: gary
  name: dind
spec:
  selector:
    app: dind
  ports:
    - port: 443
      targetPort: 2376
      protocol: TCP
  type: LoadBalancer
#kubectl apply -f dind.yml
#kubectl get pods
#kubectl get services
#kubectl get service -n gary dind -o jsonpath='{.status.loadBalancer.ingress[0].ip}'